---
deployment:
  tasks:
    - export DEPLOYPATH=/home/smartene/lithi-volt.com
    - /bin/cp dist/index.html $DEPLOYPATH
    - /bin/cp dist/output.css $DEPLOYPATH
    - /bin/cp -R dist/assets $DEPLOYPATH
